const express = require('express')
const app = express()
require('dotenv').config()
const port=process.env.PORT
const  mongoose= require('mongoose')
const cors=require('cors')
app.use(cors())
app.use(express.json())
app.use('/users',require('./apis/user.apis'))
app.get('/', (req, res) => res.send('Hello World!'))
app.listen(port, () => console.log(`Example app listening on port ${port}!`))
mongoose.connect(process.env.CONNECTION_STRING)